title: "Asit-Deva"
email: asitdeva@gmail.com
timezone: UTC
baseurl: "/meet-asit"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'personalwebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Asit Deva
    display_name: Asit
    avatar: 'assets/images/sal.png'
    email: asitdeva@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Innovation Management & Digital Transfromation. Asit has wide expereince horizon of capabilites in tech, analytics and automation."

# Social
social:
  instagram: https://www.instagram.com/asit.deva
  facebook: https://www.facebook.com/asitdeva
  twitter: https://twitter.com/asitdeva
  linkedin: https://www.linkedin.com/in/asitkdeva/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
